### PR TITLE
Use requirejs

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by sccolbert** [comment]
lgtm but what does this solve?

**Comment by blink1073** [comment]
It makes sure you have `requirejs` loaded.  In the notebook, it is included as a script tag.

**Comment by blink1073** [comment]
This will go away once we have Webpack 2.0, where we can use `System.import`.

**Comment by sccolbert** [comment]
but won't `require('requirejs')` force it to be bundled?

**Comment by blink1073** [comment]
Bundled, but not used.  The alternative would be to document that `requirejs` has to be loaded "somehow".  What do you think, @jdfreder?

**Comment by jdfreder** [comment]
I think it makes sense for this to be batteries included.  Like @blink1073 says, it will be bundled but not imported if not needed.  If someone wants to configure it themselve, they can load it into their namespace.  Besides, I think the requirejs package on npm just proxies to node require.

**Comment by sccolbert** [comment]
I have no problem with bundling it, but at that point should we even look for one in the global namespace?

**Comment by blink1073** [comment]
The notebook one has already been configured, we don't want to clobber it.

**Comment by sccolbert** [comment]
But `requirejs` is a singleton right?

**Comment by blink1073** [comment]
Ah, true: https://github.com/jrburke/r.js/blob/master/require.js#L182

**Comment by blink1073** [comment]
Updated.

**Comment by sccolbert** [comment]
:shipit:

**Comment by blink1073** [comment]
noice

**Pull request merged**
